### ISSUE TITLE
Unable to Load Chocolatey

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#113]
Hello,

Upgraded to 2.405 and was unable to load Chocolatey anymore.

Am stuck in the main page https://localhost:8080/ with the site reloading indefinitely.

**Chrome Console Log**
```
vendor.js:9 TypeError: Cannot read property 'toString' of undefined
    at Object.o.create (https://localhost:8080/habbo-web/scripts.js:1718:70)
    at Object.i.create (https://localhost:8080/habbo-web/scripts.js:1684:30)
    at i.init (https://localhost:8080/habbo-web/scripts.js:1682:40)
    at u (https://localhost:8080/habbo-web/vendor.js:9:8542)
    at https://localhost:8080/habbo-web/vendor.js:9:8714
    at p.$eval (https://localhost:8080/habbo-web/vendor.js:9:16213)
    at p.$digest (https://localhost:8080/habbo-web/vendor.js:9:14686)
    at p.$apply (https://localhost:8080/habbo-web/vendor.js:9:16496)
    at https://localhost:8080/habbo-web/vendor.js:7:11182
    at Object.a [as invoke] (https://localhost:8080/habbo-web/vendor.js:7:23805) undefined
(anonymous) @ vendor.js:9
https://localhost:8080/api/client/clienturl Failed to load resource: the server responded with a status of 401 ()
vendor.js:8 GET https://localhost:8080/extradata/private/moderations/recentModerations 401 ()
```

No Lumen Logs unfortunately.

**Comment by s150217754** [comment]
@sant0ro 

Temporarily reverting **/resources/views/habbo-web-blade.php:39** will fix the issue:

**Use**
`window.session = {!! $user !!};`

**Instead of**
`window.session = {!! json_encode($user) !!};`

**Comment by dominicusdev** [comment]
Am also experiencing this

**Comment by dominicusdev** [comment]
Temporary fix;
            @if ($user !== "null")
                window.session = {{!! json_encode($user) !!}}
            @endif

**Comment by sant0ro** [comment]
Going to fix it. Sorry about this.

**Comment by sant0ro** [comment]
Fixed.
