### ISSUE TITLE
Bugs on NUX Room

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#165]
First Reported by @BobyTS 

Bugs as follow:

1. Furniture is not included in the NUX Room (no new rows on items_base)
2. NUX Room not set as Home Room

**Chrome Logs**
```
http://localhost/api/newuser/room/select 500 (Internal Server Error)
habboapi.js:196 Choosing room failed!
```

**Lumen Logs**
```
[2017-04-12 16:45:17] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'App\Helpers\Users' not found in C:\xampp\htdocs\app\Helpers\Nux.php:108
Stack trace:
#0 C:\xampp\htdocs\app\Helpers\Nux.php(44): App\Helpers\Nux->createPoolRoom(Object(App\Models\User))
#1 C:\xampp\htdocs\vendor\illuminate\support\Facades\Facade.php(221): App\Helpers\Nux->generateRoom(Object(Illuminate\Http\Request))
#2 C:\xampp\htdocs\app\Http\Controllers\AccountController.php(102): Illuminate\Support\Facades\Facade::__callStatic('generateRoom', Array)
#3 [internal function]: App\Http\Controllers\AccountController->selectRoom(Object(Illuminate\Http\Request))
#4 C:\xampp\htdocs\vendor\illuminate\container\BoundMethod.php(29): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\vendor\illuminate\container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 C:\xampp\htdocs\vendor\illuminate\container\BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#7 C:\xampp\htdocs\vendor\illuminate\container\Container.php(531): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#8 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(741): Illuminate\Container\Container->call(Array, Array)
#9 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(707): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#10 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(681): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\AccountController), 'selectRoom', Array)
#11 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(643): Laravel\Lumen\Application->callControllerAction(Array)
#12 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(623): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#13 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#14 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#15 C:\xampp\htdocs\app\Http\Middleware\Maintenance.php(25): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#16 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(148): App\Http\Middleware\Maintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#20 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(624): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#22 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(528): Laravel\Lumen\Application->handleFoundRoute(Array)
#23 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#24 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 C:\xampp\htdocs\vendor\rdehnhardt\lumen-maintenance-mode\src\Http\Middleware\MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(148): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#30 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#31 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#32 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#33 C:\xampp\htdocs\index.php(26): Laravel\Lumen\Application->run()
#34 {main}  

```

**Comment by sant0ro** [comment]
NUX Room should be fixed on next commit.

Wait for it, please.
