### ISSUE TITLE
Error in /api/newuser/name/check

### ISSUE THREAD

**Issue by BobyTS** [sant0ro/chocolatey#174]
Name verification does not work, but we can register.

**Image :**
![newerror](https://cloud.githubusercontent.com/assets/26801809/25013529/33083bd4-2074-11e7-9de8-84f2342ce842.PNG)

**Stacktrace :**
`Call to undefined method App\Helpers\User::where()`
[lumenlog.txt](https://github.com/sant0ro/chocolatey/files/920244/lumenlog.txt)

**Comment by sant0ro** [comment]
Fixed & committed.

**Comment by BobyTS** [comment]
Not really, the script does not work correctly, it answers "OK" while I do not have insert nickname.
It should prohibit less than 4 characters and allow only certain characters #166

Checking "forbidden names" and "names already used" works

![null - ok](https://cloud.githubusercontent.com/assets/26801809/25014902/f67640e8-2079-11e7-8604-1f3eb32f3fd7.PNG)

**Comment by sant0ro** [comment]
Okay! Going to fix it.

**Comment by sant0ro** [comment]
I think I fixed it.

**Comment by sant0ro** [comment]
Going to commit.

**Comment by BobyTS** [comment]
Nice!

**Comment by BobyTS** [comment]
```
#0 /home/www/chocolatey/app/Http/Controllers/AccountController.php(108): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(8, 'Trying to get p...', '/home/www/choco...', 108, Array)
#1 [internal function]: App\Http\Controllers\AccountController->checkName(Object(Illuminate\Http\Request))
#2 /home/www/chocolatey/vendor/illuminate/container/BoundMethod.php(28): call_user_func_array(Array, Array)
#3 /home/www/chocolatey/vendor/illuminate/support/helpers.php(912): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#4 /home/www/chocolatey/vendor/illuminate/container/BoundMethod.php(86): value(Object(Closure))
#5 /home/www/chocolatey/vendor/illuminate/container/BoundMethod.php(30): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#6 /home/www/chocolatey/vendor/illuminate/container/Container.php(524): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#7 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(741): Illuminate\Container\Container->call(Array, Array)
#8 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(707): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#9 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(681): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\AccountController), 'checkName', Array)
#10 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->callControllerAction(Array)
#11 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(623): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#12 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#13 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /home/www/chocolatey/app/Http/Middleware/Maintenance.php(25): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /home/www/chocolatey/vendor/illuminate/pipeline/Pipeline.php(148): App\Http\Middleware\Maintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /home/www/chocolatey/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(624): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#21 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(528): Laravel\Lumen\Application->handleFoundRoute(Array)
#22 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#23 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 /home/www/chocolatey/vendor/rdehnhardt/lumen-maintenance-mode/src/Http/Middleware/MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /home/www/chocolatey/vendor/illuminate/pipeline/Pipeline.php(148): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 /home/www/chocolatey/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#31 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#32 /home/www/chocolatey/index.php(26): Laravel\Lumen\Application->run()
#33 {main}  
```

**Comment by BobyTS** [comment]
@sant0ro 
Returning alway false.
Cause :  !UserFacade::getUser()->isStaff)

```
#0 /home/www/chocolatey/app/Http/Controllers/AccountController.php(108): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(8, 'Trying to get p...', '/home/www/choco...', 108, Array)
#1 [internal function]: App\Http\Controllers\AccountController->checkName(Object(Illuminate\Http\Request))
#2 /home/www/chocolatey/vendor/illuminate/container/BoundMethod.php(28): call_user_func_array(Array, Array)
#3 /home/www/chocolatey/vendor/illuminate/support/helpers.php(912): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#4 /home/www/chocolatey/vendor/illuminate/container/BoundMethod.php(86): value(Object(Closure))
#5 /home/www/chocolatey/vendor/illuminate/container/BoundMethod.php(30): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#6 /home/www/chocolatey/vendor/illuminate/container/Container.php(524): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#7 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(741): Illuminate\Container\Container->call(Array, Array)
#8 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(707): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#9 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(681): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\AccountController), 'checkName', Array)
#10 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->callControllerAction(Array)
#11 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(623): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#12 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#13 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /home/www/chocolatey/app/Http/Middleware/Maintenance.php(25): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /home/www/chocolatey/vendor/illuminate/pipeline/Pipeline.php(148): App\Http\Middleware\Maintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /home/www/chocolatey/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(624): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#21 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(528): Laravel\Lumen\Application->handleFoundRoute(Array)
#22 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#23 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 /home/www/chocolatey/vendor/rdehnhardt/lumen-maintenance-mode/src/Http/Middleware/MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /home/www/chocolatey/vendor/illuminate/pipeline/Pipeline.php(148): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 /home/www/chocolatey/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#31 /home/www/chocolatey/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#32 /home/www/chocolatey/index.php(26): Laravel\Lumen\Application->run()
#33 {main}  
```

**Comment by sant0ro** [comment]
Calm down @BobyTS I already saw this. Going to fix.

**Comment by sant0ro** [comment]
Fixed. going to commit.

**Comment by BobyTS** [comment]
Sorry, but I thought that without quoting you, you would not have been notified

**Comment by sant0ro** [comment]
I receive notifications without citation ;) Everyone subscribed receive.
