### ISSUE TITLE
Registration Issue

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#54]
Hi there,

There seems to be an issue registering an account.

Upon clicking the Register button, the following error shows:
`Oops! Something went wrong. You can try again in a few moments. We're looking into it.`

Btw, the account has been successfully created in the Database.

**Chrome Console Log**
```
POST http://localhost:8080/api/public/registration/new 500 ()
vendor.js:2883 XHR finished loading: POST "http://localhost:8080/api/public/registration/new".
```

**Lumen Log**
```
[2017-02-28 09:38:32] lumen.ERROR: ErrorException: Undefined index: rank in C:\xampp\htdocs\app\Models\User.php:238
Stack trace:
#0 C:\xampp\htdocs\app\Models\User.php(238): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 238, Array)
#1 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Concerns\HasAttributes.php(431): App\Models\User->getTraitsAttribute(NULL)
#2 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Concerns\HasAttributes.php(443): Illuminate\Database\Eloquent\Model->mutateAttribute('traits', NULL)
#3 C:\xampp\htdocs\vendor\sofa\eloquence\src\Mappable.php(583): Illuminate\Database\Eloquent\Model->mutateAttributeForArray('traits', NULL)
#4 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Concerns\HasAttributes.php(101): App\Models\User->mutateAttributeForArray('traits', NULL)
#5 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Model.php(884): Illuminate\Database\Eloquent\Model->attributesToArray()
#6 C:\xampp\htdocs\vendor\sofa\hookable\src\Hookable.php(170): Illuminate\Database\Eloquent\Model->toArray()
#7 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Http\ResponseFactory.php(38): App\Models\User->toArray()
#8 C:\xampp\htdocs\app\Http\Controllers\LoginController.php(74): Laravel\Lumen\Http\ResponseFactory->json(Object(App\Models\User))
#9 [internal function]: App\Http\Controllers\LoginController->register(Object(Illuminate\Http\Request))
#10 C:\xampp\htdocs\vendor\illuminate\container\BoundMethod.php(28): call_user_func_array(Array, Array)
#11 C:\xampp\htdocs\vendor\illuminate\support\helpers.php(912): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#12 C:\xampp\htdocs\vendor\illuminate\container\BoundMethod.php(86): value(Object(Closure))
#13 C:\xampp\htdocs\vendor\illuminate\container\BoundMethod.php(30): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#14 C:\xampp\htdocs\vendor\illuminate\container\Container.php(524): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#15 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(743): Illuminate\Container\Container->call(Array, Array)
#16 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(709): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#17 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(683): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\LoginController), 'register', Array)
#18 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(645): Laravel\Lumen\Application->callControllerAction(Array)
#19 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(625): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#20 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#21 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 C:\xampp\htdocs\app\Http\Middleware\Maintenance.php(28): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#23 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(148): App\Http\Middleware\Maintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#27 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(780): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#28 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(626): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#29 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(528): Laravel\Lumen\Application->handleFoundRoute(Array)
#30 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#31 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 C:\xampp\htdocs\vendor\rdehnhardt\lumen-maintenance-mode\src\Http\Middleware\MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#33 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(148): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#37 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(780): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#38 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#39 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#40 C:\xampp\htdocs\index.php(26): Laravel\Lumen\Application->run()
#41 {main}  
```

Thanks!

**Comment by sant0ro** [comment]
Oh, that's a last version issue. Will solve it now.

**Comment by sant0ro** [comment]
Fixed. Will commit to binaries soon as possible.
