### ISSUE TITLE
NUX Issue

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#67]
Hi,

Just updated the files manually to d43520e. Room don't get generated fully.

**Example:**
![Room](http://i.imgur.com/oehQ2m0.png)

**Chrome Console Log**
![Log](http://i.imgur.com/BGUQ0m2.png)

No error log on lumen end. 

Haven't try the other rooms. Will try it later.

**Comment by sant0ro** [comment]
That's weird! Can you check if all the items were created? on the Database?

**Comment by sant0ro** [comment]
It seems that it's only inserting the frist item of Wall and Floor

**Comment by sant0ro** [comment]
Oh I see i did a mistake.

**Comment by sant0ro** [comment]
Fixed.

**Comment by s150217754** [comment]
Also, the rooms table is missing the owner_id and owner_name. Didn't add it when I gave you the SQLs so you'll have to add it yourself.

**Comment by sant0ro** [comment]
Oh I see. Fixing it.

**Comment by s150217754** [comment]
Updated to 90ce2a2. Seems like more problems, rooms and furniture rows don't get created.

**Chrome Console Log**
```
POST https://beta.sotel.gq:8443/api/newuser/room/select 500 ()
habboapi.js:9 Choosing room failed!
```

**Lumen Logs**
```
[2017-03-06 05:17:26] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 9 passed to App\Models\Room::store() must be of the type integer, string given, called in C:\xampp\htdocs\app\Helpers\Nux.php on line 60 in C:\xampp\htdocs\app\Models\Room.php:143
Stack trace:
#0 C:\xampp\htdocs\app\Helpers\Nux.php(60): App\Models\Room->store('User1's room'', 'User1 has entere...', 'model_h', 25, 12, 610, 2403, 4, 'User1')
#1 C:\xampp\htdocs\app\Helpers\Nux.php(42): App\Helpers\Nux->createBedRoom(Object(App\Models\User))
#2 C:\xampp\htdocs\vendor\illuminate\support\Facades\Facade.php(221): App\Helpers\Nux->generateRoom(Object(Illuminate\Http\Request))
#3 C:\xampp\htdocs\app\Http\Controllers\AccountController.php(99): Illuminate\Support\Facades\Facade::__callStatic('generateRoom', Array)
#4 [internal function]: App\Http\Controllers\AccountController->selectRoom(Object(Illuminate\Http\Request))
#5 C:\xampp\htdocs\vendor\illuminate\container\BoundMethod.php(28): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\vendor\illuminate\support\helpers.php(912): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#7 C:\xampp\htdocs\vendor\illuminate\container\BoundMethod.php(86): value(Object(Closure))
#8 C:\xampp\htdocs\vendor\illuminate\container\BoundMethod.php(30): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#9 C:\xampp\htdocs\vendor\illuminate\container\Container.php(524): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#10 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(743): Illuminate\Container\Container->call(Array, Array)
#11 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(709): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#12 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(683): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\AccountController), 'selectRoom', Array)
#13 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(645): Laravel\Lumen\Application->callControllerAction(Array)
#14 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(625): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#15 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#16 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 C:\xampp\htdocs\app\Http\Middleware\Authenticate.php(50): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#18 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(148): App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 C:\xampp\htdocs\app\Http\Middleware\Maintenance.php(28): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#22 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(148): App\Http\Middleware\Maintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(780): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(626): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#28 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(528): Laravel\Lumen\Application->handleFoundRoute(Array)
#29 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#30 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#31 C:\xampp\htdocs\vendor\rdehnhardt\lumen-maintenance-mode\src\Http\Middleware\MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#32 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(148): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#36 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(780): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#37 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#38 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#39 C:\xampp\htdocs\index.php(26): Laravel\Lumen\Application->run()
#40 {main}  
```

**Comment by sant0ro** [comment]
Oh i see. Wait.

**Comment by sant0ro** [comment]
Fixed.

**Comment by s150217754** [comment]
@sant0ro Created separate ticket on NUX - #68
