### ISSUE TITLE
Unable to load Rooms page

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#81]
Hi,

Unable to load Rooms page due to some tags issue:

**Lumen Log:**
```
[2017-03-13 05:53:50] lumen.ERROR: ErrorException: Undefined offset: 1 in /sandbox/app/Models/Room.php:172
Stack trace:
#0 /sandbox/app/Models/Room.php(172): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(8, 'Undefined offse...', '/sandbox/app/Mod...', 172, Array)
#1 /sandbox/vendor/illuminate/database/Eloquent/Concerns/HasAttributes.php(432): App\Models\Room->getTagsAttribute('')
#2 /sandbox/vendor/illuminate/database/Eloquent/Concerns/HasAttributes.php(444): Illuminate\Database\Eloquent\Model->mutateAttribute('tags', '')
#3 /sandbox/vendor/sofa/eloquence/src/Mappable.php(583): Illuminate\Database\Eloquent\Model->mutateAttributeForArray('tags', '')
#4 /sandbox/vendor/illuminate/database/Eloquent/Concerns/HasAttributes.php(150): App\Models\Room->mutateAttributeForArray('tags', '')
#5 /sandbox/vendor/illuminate/database/Eloquent/Concerns/HasAttributes.php(88): Illuminate\Database\Eloquent\Model->addMutatedAttributesToArray(Array, Array)
#6 /sandbox/vendor/illuminate/database/Eloquent/Model.php(884): Illuminate\Database\Eloquent\Model->attributesToArray()
#7 /sandbox/vendor/sofa/hookable/src/Hookable.php(170): Illuminate\Database\Eloquent\Model->toArray()
#8 /sandbox/vendor/illuminate/support/Collection.php(1316): App\Models\Room->toArray()
#9 [internal function]: Illuminate\Support\Collection->Illuminate\Support\{closure}(Object(App\Models\Room))
#10 /sandbox/vendor/illuminate/support/Collection.php(1317): array_map(Object(Closure), Array)
#11 /sandbox/vendor/laravel/lumen-framework/src/Http/ResponseFactory.php(38): Illuminate\Support\Collection->toArray()
#12 /sandbox/app/Http/Controllers/RoomsController.php(35): Laravel\Lumen\Http\ResponseFactory->json(Object(Illuminate\Database\Eloquent\Collection), 200, Array, 64)
#13 [internal function]: App\Http\Controllers\RoomsController->getLeader(Object(Illuminate\Http\Request), 'hhus', 'daily', 'latest.json')
#14 /sandbox/vendor/illuminate/container/BoundMethod.php(28): call_user_func_array(Array, Array)
#15 /sandbox/vendor/illuminate/support/helpers.php(912): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#16 /sandbox/vendor/illuminate/container/BoundMethod.php(86): value(Object(Closure))
#17 /sandbox/vendor/illuminate/container/BoundMethod.php(30): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#18 /sandbox/vendor/illuminate/container/Container.php(524): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#19 /sandbox/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(741): Illuminate\Container\Container->call(Array, Array)
#20 /sandbox/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(707): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#21 /sandbox/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(681): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\RoomsController), 'getLeader', Array)
#22 /sandbox/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->callControllerAction(Array)
#23 /sandbox/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(628): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#24 /sandbox/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(598): Laravel\Lumen\Application->handleFoundRoute(Array)
#25 /sandbox/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(532): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#26 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#27 /sandbox/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 /sandbox/vendor/rdehnhardt/lumen-maintenance-mode/src/Http/Middleware/MaintenanceModeMiddleware.php(48): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /sandbox/vendor/illuminate/pipeline/Pipeline.php(148): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /sandbox/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 /sandbox/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /sandbox/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 /sandbox/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#35 /sandbox/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#36 /sandbox/index.php(26): Laravel\Lumen\Application->run()
#37 {main}  

```

**Comment by s150217754** [comment]
@sant0ro Fixed. See Pull request. Close issue when pulled.

**Comment by s150217754** [comment]
Did some research on this issue:

Rooms with either one or no tags would result in a Undefined array. @sant0ro

**Comment by sant0ro** [comment]
Okay, It's quite easy to solve. My fault.
